// ─── Stellar Nebula Nomad — Subgraph Event Mapping Handlers ─────────────────
//
// Processes on-chain Soroban contract events and materializes them into the
// GraphQL entities defined in schema.graphql. Each handler decodes the event
// body via the contract ABI, loads or creates the relevant entity, mutates
// state, and persists the result back to the store.
//
// Target runtime: Graph Node with Soroban event ingestion (assemblyscript).

import { BigInt, Bytes, ByteArray, crypto, store, log } from "@graphprotocol/graph-ts";
import {
  Player,
  Ship,
  NebulaScan,
  HarvestRecord,
  Session,
  MarketplaceListing,
  DEXOffer,
  TradeRecord,
  Alliance,
  AllianceMember,
  Proposal,
  VoteRecord,
  DaoConfig,
  StakeRecord,
  TreasureVault,
  Blueprint,
  Referral,
  TreasuryTransfer,
} from "../generated/schema";

// ─── ABI-generated event types (imported from graph codegen output) ────────
//
// The following types are auto-generated by `graph codegen` from the ABI JSON
// placed at ./abis/StellarNebulaNomad.json. We re-export the minimal set of
// value-decoding helpers needed by the handlers below.
//
// In a real build pipeline, these come from:
//   import { ShipMinted, ShipXfer, ... } from "../generated/StellarNebulaNomad/StellarNebulaNomad";
//
// For clarity, each handler documents the event body shape it expects.

// ─── Helpers ────────────────────────────────────────────────────────────────

function ensurePlayer(id: string, now: BigInt): Player {
  let player = Player.load(id);
  if (player == null) {
    player = new Player(id);
    player.profileId = null;
    player.totalScans = 0;
    player.essenceEarned = BigInt.fromI32(0);
    player.createdAt = now;
    player.lastUpdatedAt = now;
    player.save();
  } else {
    player.lastUpdatedAt = now;
    player.save();
  }
  return player as Player;
}

function ensureShip(
  id: string,
  ownerId: string,
  now: BigInt
): Ship {
  let ship = Ship.load(id);
  if (ship == null) {
    ship = new Ship(id);
    ship.owner = ownerId;
    ship.shipType = "";
    ship.hull = 0;
    ship.scannerPower = 0;
    ship.level = 1;
    ship.scanRange = 0;
    ship.metadataCID = null;
    ship.mintedAt = now;
    ship.save();
  }
  return ship as Ship;
}

function makeId(...parts: string[]): string {
  let joined = parts.join("-");
  let hash = crypto.keccak256(String.UTF8.encode(joined));
  return hash.toHexString();
}

function eventTimestamp(): BigInt {
  // In a real handler, use `block.timestamp` from the event context.
  return BigInt.fromI32(0);
}

// ─── Ship NFT Handlers ─────────────────────────────────────────────────────

/**
 * Handles `("ship", "minted")` → (id: u64, owner: Address, ship_type: Symbol,
 *                                  hull: u32, scanner_power: u32)
 */
export function handleShipMinted(event: any): void {
  const now = eventTimestamp();
  const shipId = event.parameters[0].value.toU64().toString();
  const ownerAddress = event.parameters[1].value.toAddress().toHexString();
  const shipType = event.parameters[2].value.toSymbol().toString();
  const hull = event.parameters[3].value.toU32();
  const scannerPower = event.parameters[4].value.toU32();

  ensurePlayer(ownerAddress, now);
  const ship = ensureShip(shipId, ownerAddress, now);
  ship.shipType = shipType;
  ship.hull = i32(hull);
  ship.scannerPower = i32(scannerPower);
  ship.save();
}

/**
 * Handles `("ship", "xfer")` → (ship_id: u64, from: Address, to: Address)
 */
export function handleShipTransfer(event: any): void {
  const now = eventTimestamp();
  const shipId = event.parameters[0].value.toU64().toString();
  const toAddress = event.parameters[2].value.toAddress().toHexString();

  ensurePlayer(toAddress, now);

  const ship = Ship.load(shipId);
  if (ship != null) {
    ship.owner = toAddress;
    ship.save();
  } else {
    log.warning("Ship {} not found on transfer", [shipId]);
  }
}

// ─── Nebula Generation Handlers ────────────────────────────────────────────

/**
 * Handles `("NebulaGen", "generated")` → (ship_id: u64, layout_hash: BytesN<32>,
 *                                          size: u32)
 */
export function handleNebulaGenerated(event: any): void {
  const now = eventTimestamp();
  const shipId = event.parameters[0].value.toU64().toString();
  const layoutHash = event.parameters[1].value.toBytes().toHexString();
  const size = event.parameters[2].value.toU32();

  ensurePlayer(event.transaction.from.toHexString(), now);

  const scanId = makeId("scan", shipId, layoutHash, now.toString());
  const scan = new NebulaScan(scanId);
  scan.player = event.transaction.from.toHexString();
  scan.ship = shipId;
  scan.layoutHash = layoutHash;
  scan.rarity = "Unknown";
  scan.totalEnergy = 0;
  scan.anomalyCount = 0;
  scan.scannedAt = now;
  scan.save();
}

/**
 * Handles `("neb_gen", "expired")` → (ship_id: u64)
 */
export function handleNebulaExpired(event: any): void {
  const shipId = event.parameters[0].value.toU64().toString();
  log.info("Nebula layout expired for ship {}", [shipId]);
}

/**
 * Handles `("neb_gen", "cleaned")` → (ship_id: u64)
 */
export function handleNebulaCleaned(event: any): void {
  const shipId = event.parameters[0].value.toU64().toString();
  log.info("Nebula layout cleaned for ship {}", [shipId]);
}

// ─── Resource Minting Handler ──────────────────────────────────────────────

/**
 * Handles `("Minter", "minted")` → (caller: Address, resource_type: Symbol,
 *                                    amount: i128)
 */
export function handleResourceMinted(event: any): void {
  const now = eventTimestamp();
  const caller = event.parameters[0].value.toAddress().toHexString();
  const resourceType = event.parameters[1].value.toSymbol().toString();
  const amount = event.parameters[2].value.toBigInt();

  ensurePlayer(caller, now);

  const record = new HarvestRecord(makeId("harvest", caller, now.toString()));
  record.scan = "";
  record.ship = "";
  record.resourceType = resourceType;
  record.amount = amount;
  record.harvestedAt = now;
  record.save();
}

// ─── Marketplace Handlers ──────────────────────────────────────────────────

/**
 * Handles `("market", "listed")` → (seller: Address, ship_id: u64, price: i128)
 */
export function handleMarketListed(event: any): void {
  const now = eventTimestamp();
  const seller = event.parameters[0].value.toAddress().toHexString();
  const shipId = event.parameters[1].value.toU64().toString();
  const price = event.parameters[2].value.toBigInt();

  ensurePlayer(seller, now);

  const listingId = makeId("listing", seller, shipId, now.toString());
  const listing = new MarketplaceListing(listingId);
  listing.ship = shipId;
  listing.seller = seller;
  listing.price = price;
  listing.active = true;
  listing.listedAt = now;
  listing.closedAt = null;
  listing.buyer = null;
  listing.royaltyAmount = null;
  listing.sellerProceeds = null;
  listing.save();
}

/**
 * Handles `("market", "sold")` → (buyer: Address, seller: Address, ship_id: u64,
 *                                  price: i128, royalty: i128, seller_proceeds: i128)
 */
export function handleMarketSold(event: any): void {
  const now = eventTimestamp();
  const buyer = event.parameters[0].value.toAddress().toHexString();
  const seller = event.parameters[1].value.toAddress().toHexString();
  const shipId = event.parameters[2].value.toU64().toString();
  const price = event.parameters[3].value.toBigInt();
  const royalty = event.parameters[4].value.toBigInt();
  const sellerProceeds = event.parameters[5].value.toBigInt();

  ensurePlayer(buyer, now);

  const listingId = makeId("listing", seller, shipId, "");
  // Search for active listing — in production, iterate or use derived store queries.
  // For this handler, we reconstruct from event data and update.
  const listing = new MarketplaceListing(listingId);
  listing.ship = shipId;
  listing.seller = seller;
  listing.price = price;
  listing.active = false;
  listing.listedAt = now;
  listing.closedAt = now;
  listing.buyer = buyer;
  listing.royaltyAmount = royalty;
  listing.sellerProceeds = sellerProceeds;
  listing.save();

  // Update ship ownership
  const ship = Ship.load(shipId);
  if (ship != null) {
    ship.owner = buyer;
    ship.save();
  }
}

/**
 * Handles `("market", "cancel")` → (seller: Address, ship_id: u64)
 */
export function handleMarketCancelled(event: any): void {
  const now = eventTimestamp();
  const seller = event.parameters[0].value.toAddress().toHexString();
  const shipId = event.parameters[1].value.toU64().toString();

  const listingId = makeId("listing", seller, shipId, "");
  const listing = MarketplaceListing.load(listingId);
  if (listing != null) {
    listing.active = false;
    listing.closedAt = now;
    listing.save();
  }
}

// ─── DEX Handlers ──────────────────────────────────────────────────────────

/**
 * Handles `("dex", "listed")` → (offer_id: u64, player: Address, resource: Symbol,
 *                                 listed_amount: i128, min_price: i128)
 */
export function handleDEXListed(event: any): void {
  const now = eventTimestamp();
  const offerId = event.parameters[0].value.toU64().toString();
  const player = event.parameters[1].value.toAddress().toHexString();
  const resource = event.parameters[2].value.toSymbol().toString();
  const listedAmount = event.parameters[3].value.toBigInt();
  const minPrice = event.parameters[4].value.toBigInt();

  ensurePlayer(player, now);

  const offer = new DEXOffer(offerId);
  offer.player = player;
  offer.resourceType = resource;
  offer.listedAmount = listedAmount;
  offer.minPrice = minPrice;
  offer.active = true;
  offer.listedAt = now;
  offer.save();
}

/**
 * Handles `("dex", "canceld")` → (offer_id: u64, owner: Address)
 */
export function handleDEXCancelled(event: any): void {
  const offerId = event.parameters[0].value.toU64().toString();
  const offer = DEXOffer.load(offerId);
  if (offer != null) {
    offer.active = false;
    offer.save();
  }
}

// ─── Governance Handlers ───────────────────────────────────────────────────

/**
 * Handles `("gov", "prop_crtd")` → (proposal_id: u64, creator: Address)
 */
export function handleProposalCreated(event: any): void {
  const now = eventTimestamp();
  const proposalId = event.parameters[0].value.toU64().toString();
  const creator = event.parameters[1].value.toAddress().toHexString();

  ensurePlayer(creator, now);

  const proposal = new Proposal(proposalId);
  proposal.proposer = creator;
  proposal.description = "";
  proposal.votingStartLedger = now;
  proposal.votingEndLedger = BigInt.fromI32(0);
  proposal.timelockEndLedger = null;
  proposal.status = "Active";
  proposal.forVotes = BigInt.fromI32(0);
  proposal.againstVotes = BigInt.fromI32(0);
  proposal.createdAt = now;
  proposal.save();
}

/**
 * Handles `("gov", "vote_cast")` → (proposal_id: u64, voter: Address,
 *                                    support: bool, essence_weight: i128)
 */
export function handleVoteCast(event: any): void {
  const now = eventTimestamp();
  const proposalId = event.parameters[0].value.toU64().toString();
  const voter = event.parameters[1].value.toAddress().toHexString();
  const support = event.parameters[2].value.toBoolean();
  const power = event.parameters[3].value.toBigInt();

  ensurePlayer(voter, now);

  const voteId = makeId("vote", proposalId, voter);
  const vote = new VoteRecord(voteId);
  vote.proposal = proposalId;
  vote.voter = voter;
  vote.direction = support ? "For" : "Against";
  vote.power = power;
  vote.votedAt = now;
  vote.save();

  // Update proposal tallies
  const proposal = Proposal.load(proposalId);
  if (proposal != null) {
    if (support) {
      proposal.forVotes = proposal.forVotes.plus(power);
    } else {
      proposal.againstVotes = proposal.againstVotes.plus(power);
    }
    proposal.save();
  }
}

/**
 * Handles `("dao", "prop_crt")` → (proposal_id: u64, proposer: Address)
 */
export function handleDAOProposalCreated(event: any): void {
  // Reuses the same proposal creation logic; DAO proposals have additional
  // timelock metadata that may be emitted in separate events.
  handleProposalCreated(event);
}

/**
 * Handles `("dao", "vote")` → (proposal_id: u64, voter: Address, power: i128)
 */
export function handleDAOVote(event: any): void {
  // DAO vote events don't carry direction; default to "For" — direction
  // can be enriched by querying the on-chain vote record.
  const now = eventTimestamp();
  const proposalId = event.parameters[0].value.toU64().toString();
  const voter = event.parameters[1].value.toAddress().toHexString();
  const power = event.parameters[2].value.toBigInt();

  ensurePlayer(voter, now);

  const voteId = makeId("dao-vote", proposalId, voter);
  const vote = VoteRecord.load(voteId);
  if (vote == null) {
    const newVote = new VoteRecord(voteId);
    newVote.proposal = proposalId;
    newVote.voter = voter;
    newVote.direction = "For";
    newVote.power = power;
    newVote.votedAt = now;
    newVote.save();
  }
}

/**
 * Handles `("dao", "exec")` → (proposal_id: u64)
 */
export function handleDAOExecuted(event: any): void {
  const proposalId = event.parameters[0].value.toU64().toString();
  const proposal = Proposal.load(proposalId);
  if (proposal != null) {
    proposal.status = "Executed";
    proposal.save();
  }
}

/**
 * Handles `("dao", "treas")` → (recipient: Address, amount: i128)
 */
export function handleTreasuryTransfer(event: any): void {
  const now = eventTimestamp();
  const recipient = event.parameters[0].value.toAddress().toHexString();
  const amount = event.parameters[1].value.toBigInt();

  ensurePlayer(recipient, now);

  const transfer = new TreasuryTransfer(makeId("treasury", recipient, now.toString()));
  transfer.recipient = recipient;
  transfer.amount = amount;
  transfer.timestamp = now;
  transfer.save();
}

// ─── Alliance Handlers ─────────────────────────────────────────────────────

/**
 * Handles `("alliance", "founded")` → (alliance_id: u64, name: String, founder: Address)
 */
export function handleAllianceFounded(event: any): void {
  const now = eventTimestamp();
  const allianceId = event.parameters[0].value.toU64().toString();
  const name = event.parameters[1].value.toString();
  const founder = event.parameters[2].value.toAddress().toHexString();

  ensurePlayer(founder, now);

  const alliance = new Alliance(allianceId);
  alliance.name = name;
  alliance.founder = founder;
  alliance.treasury = BigInt.fromI32(0);
  alliance.votingThreshold = 0;
  alliance.isActive = true;
  alliance.createdAt = now;
  alliance.save();
}

/**
 * Handles `("alliance", "joined")` → (alliance_id: u64, player: Address)
 */
export function handleAllianceJoined(event: any): void {
  const now = eventTimestamp();
  const allianceId = event.parameters[0].value.toU64().toString();
  const player = event.parameters[1].value.toAddress().toHexString();

  ensurePlayer(player, now);

  const memberId = makeId("member", allianceId, player);
  const member = new AllianceMember(memberId);
  member.alliance = allianceId;
  member.player = player;
  member.joinedAt = now;
  member.contribution = BigInt.fromI32(0);
  member.save();
}

/**
 * Handles `("alliance", "left")` → (alliance_id: u64, player: Address)
 */
export function handleAllianceLeft(event: any): void {
  const allianceId = event.parameters[0].value.toU64().toString();
  const player = event.parameters[1].value.toAddress().toHexString();

  const memberId = makeId("member", allianceId, player);
  const member = AllianceMember.load(memberId);
  if (member != null) {
    store.remove("AllianceMember", memberId);
  }
}

/**
 * Handles `("alliance", "contrib")` → (alliance_id: u64, player: Address,
 *                                       amount: i128, new_treasury: i128)
 */
export function handleAllianceContribution(event: any): void {
  const now = eventTimestamp();
  const allianceId = event.parameters[0].value.toU64().toString();
  const player = event.parameters[1].value.toAddress().toHexString();
  const amount = event.parameters[2].value.toBigInt();
  const newTreasury = event.parameters[3].value.toBigInt();

  ensurePlayer(player, now);

  // Update alliance treasury
  const alliance = Alliance.load(allianceId);
  if (alliance != null) {
    alliance.treasury = newTreasury;
    alliance.save();
  }

  // Update member contribution
  const memberId = makeId("member", allianceId, player);
  const member = AllianceMember.load(memberId);
  if (member != null) {
    member.contribution = member.contribution.plus(amount);
    member.save();
  }
}

// ─── Staking Handlers ──────────────────────────────────────────────────────

/**
 * Handles `("stake", "staked")` → (staker: Address, amount: i128)
 */
export function handleStaked(event: any): void {
  const now = eventTimestamp();
  const staker = event.parameters[0].value.toAddress().toHexString();
  const amount = event.parameters[1].value.toBigInt();

  ensurePlayer(staker, now);

  const stake = new StakeRecord(makeId("stake", staker, now.toString()));
  stake.staker = staker;
  stake.amount = amount;
  stake.createdLedger = now;
  stake.unlockLedger = BigInt.fromI32(0);
  stake.save();
}

/**
 * Handles `("stake", "unstaked")` → (staker: Address, amount: i128)
 */
export function handleUnstaked(event: any): void {
  const staker = event.parameters[0].value.toAddress().toHexString();
  const amount = event.parameters[1].value.toBigInt();

  // Find and remove the most recent active stake for this staker.
  // In production, use a deterministic stake ID scheme.
  log.info("Unstaked {} by {}", [amount.toString(), staker]);
}

// ─── Vault Handlers ────────────────────────────────────────────────────────

/**
 * Handles `("vault", "deposit")` → (vault_id: u64, owner: Address, ship_id: u64,
 *                                    amount: i128, lock_until: u32)
 */
export function handleVaultDeposit(event: any): void {
  const now = eventTimestamp();
  const vaultId = event.parameters[0].value.toU64().toString();
  const owner = event.parameters[1].value.toAddress().toHexString();
  const shipId = event.parameters[2].value.toU64().toString();
  const amount = event.parameters[3].value.toBigInt();
  const lockUntil = event.parameters[4].value.toBigInt();

  ensurePlayer(owner, now);

  const vault = new TreasureVault(vaultId);
  vault.owner = owner;
  vault.ship = shipId;
  vault.amount = amount;
  vault.lockUntil = lockUntil;
  vault.bonusMultiplier = 0;
  vault.claimed = false;
  vault.depositedAt = now;
  vault.save();
}

/**
 * Handles `("vault", "claimed")` → (vault_id: u64, owner: Address, total_payout: i128)
 */
export function handleVaultClaimed(event: any): void {
  const vaultId = event.parameters[0].value.toU64().toString();
  const vault = TreasureVault.load(vaultId);
  if (vault != null) {
    vault.claimed = true;
    vault.save();
  }
}

// ─── Profile Handlers ──────────────────────────────────────────────────────

/**
 * Handles `("nomad", "joined")` → (owner: Address, id: u64)
 */
export function handlePlayerJoined(event: any): void {
  const now = eventTimestamp();
  const owner = event.parameters[0].value.toAddress().toHexString();
  const profileId = event.parameters[1].value.toU64();

  const player = ensurePlayer(owner, now);
  player.profileId = profileId;
  player.save();
}

/**
 * Handles `("profile", "updated")` → (caller: Address, profile_id: u64,
 *                                      total_scans: u32, essence_earned: i128)
 */
export function handleProfileUpdated(event: any): void {
  const now = eventTimestamp();
  const caller = event.parameters[0].value.toAddress().toHexString();
  const totalScans = event.parameters[2].value.toU32();
  const essenceEarned = event.parameters[3].value.toBigInt();

  const player = ensurePlayer(caller, now);
  player.totalScans = i32(totalScans);
  player.essenceEarned = essenceEarned;
  player.lastUpdatedAt = now;
  player.save();
}

// ─── Metadata Handler ──────────────────────────────────────────────────────

/**
 * Handles `("meta", "updated")` → (token_id: u64, cid: Bytes, caller: Address)
 */
export function handleMetadataUpdated(event: any): void {
  const tokenId = event.parameters[0].value.toU64().toString();
  const cid = event.parameters[1].value.toBytes().toHexString();

  const ship = Ship.load(tokenId);
  if (ship != null) {
    ship.metadataCID = cid;
    ship.save();
  }
}

// ─── RBAC Handlers ─────────────────────────────────────────────────────────

/**
 * Handles `("rbac", "grant")` → (role: Symbol, grantee: Address, expiry: Option<u32>)
 */
export function handleRBACGrant(event: any): void {
  const role = event.parameters[0].value.toSymbol().toString();
  const grantee = event.parameters[1].value.toAddress().toHexString();
  log.info("RBAC role {} granted to {}", [role, grantee]);
}

/**
 * Handles `("rbac", "revoke")` → (role: Symbol, revokee: Address)
 */
export function handleRBACRevoke(event: any): void {
  const role = event.parameters[0].value.toSymbol().toString();
  const revokee = event.parameters[1].value.toAddress().toHexString();
  log.info("RBAC role {} revoked from {}", [role, revokee]);
}

// ─── Economics Handler ─────────────────────────────────────────────────────

/**
 * Handles `("econ", "supply")` → (total_supply: i128, circulating_supply: i128,
 *                                  staked_supply: i128)
 */
export function handleEconomicSupply(event: any): void {
  const totalSupply = event.parameters[0].value.toBigInt();
  const circulatingSupply = event.parameters[1].value.toBigInt();
  const stakedSupply = event.parameters[2].value.toBigInt();
  log.info(
    "Economic supply — total: {}, circulating: {}, staked: {}",
    [totalSupply.toString(), circulatingSupply.toString(), stakedSupply.toString()]
  );
}

// ─── Bond Handlers ─────────────────────────────────────────────────────────

/**
 * Handles `("bond", "created")` → (bond_id: u64, initiator: Address, partner: Address)
 */
export function handleBondCreated(event: any): void {
  const bondId = event.parameters[0].value.toU64().toString();
  const initiator = event.parameters[1].value.toAddress().toHexString();
  const partner = event.parameters[2].value.toAddress().toHexString();
  log.info("Bond {} created between {} and {}", [bondId, initiator, partner]);
}

/**
 * Handles `("bond", "accepted")` → (bond_id: u64, partner: Address)
 */
export function handleBondAccepted(event: any): void {
  const bondId = event.parameters[0].value.toU64().toString();
  const partner = event.parameters[1].value.toAddress().toHexString();
  log.info("Bond {} accepted by {}", [bondId, partner]);
}

/**
 * Handles `("bond", "dissolve")` → (bond_id: u64, caller: Address)
 */
export function handleBondDissolved(event: any): void {
  const bondId = event.parameters[0].value.toU64().toString();
  const caller = event.parameters[1].value.toAddress().toHexString();
  log.info("Bond {} dissolved by {}", [bondId, caller]);
}
